### ISSUE TITLE
Do you have any recommended reading on the topic of functional programming?

### ISSUE THREAD

**Issue by keb** [developit/ama#2]
I guess more specifically with JS, but any rec'd reading is welcome. :)

**Comment by developit** [comment]
That's a tricky one - I actually don't read as much about programming as I should. I think the last purely technical book I read was Ilya's [High Performance Browser Networking](https://hpbn.co/).

I was also made aware of a book that I am pretty excited to read, which is called [Crafting Interpreters](https://craftinginterpreters.com)

**Comment by keb** [comment]
Awesome, thank you for Ilya's book. I'd never heard of it, and will add it to my list of growing [free web books](https://keb.now.sh/books/)! 📚 

I read bits of Bob Nystrom's Game Programming Patterns and thought it was great. Crafting Interpreters does look awesome.

Thank you and thank you so much for creating Preact among a bunch of other great (and tiny) tools!
